### ISSUE TITLE
Error: Could not find a production build in the '/Users/nick/dev/handbook/.next' directory

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/handbook#56]
I followed the instructions in the readme to run locally on a fresh checkout and got the following error:

```sh
nick@Nicks-MBP dev % git clone git@github.com:sourcegraph/handbook.git
Cloning into 'handbook'...
remote: Enumerating objects: 26624, done.
remote: Counting objects: 100% (1702/1702), done.
remote: Compressing objects: 100% (882/882), done.
remote: Total 26624 (delta 994), reused 1268 (delta 784), pack-reused 24922
Receiving objects: 100% (26624/26624), 7.81 MiB | 12.29 MiB/s, done.
Resolving deltas: 100% (15579/15579), done.
nick@Nicks-MBP dev % cd handbook
nick@Nicks-MBP handbook % yarn
yarn install v1.22.11
[1/4] 🔍  Resolving packages...
warning Resolution field "unist-util-visit-parents@5.1.0" is incompatible with requested version "unist-util-visit-parents@^4.0.0"
warning Resolution field "unist-util-is@5.1.1" is incompatible with requested version "unist-util-is@^4.0.0"
warning Resolution field "unist-util-visit-parents@5.1.0" is incompatible with requested version "unist-util-visit-parents@^3.0.0"
warning Resolution field "unist-util-visit-parents@5.1.0" is incompatible with requested version "unist-util-visit-parents@^4.0.0"
warning Resolution field "unist-util-is@5.1.1" is incompatible with requested version "unist-util-is@^4.0.0"
warning Resolution field "unist-util-visit-parents@5.1.0" is incompatible with requested version "unist-util-visit-parents@^4.0.0"
[2/4] 🚚  Fetching packages...
[###############################################################################################################################################################-] 797/[###############################################################################################################################################################-] 798/[#############info @next/swc-darwin-arm64@11.1.2: The CPU architecture "x64" is incompatible with this module.
info "@next/swc-darwin-arm64@11.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info @next/swc-linux-x64-gnu@11.1.2: The platform "darwin" is incompatible with this module.
info "@next/swc-linux-x64-gnu@11.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info @next/swc-win32-x64-msvc@11.1.2: The platform "darwin" is incompatible with this module.
info "@next/swc-win32-x64-msvc@11.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] 🔗  Linking dependencies...
warning " > bootstrap@5.1.1" has unmet peer dependency "@popperjs/core@^2.10.1".
warning "next > styled-jsx > @babel/plugin-syntax-jsx@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > ts-node@10.2.1" has unmet peer dependency "@types/node@*".
[4/4] 🔨  Building fresh packages...
✨  Done in 15.69s.
nick@Nicks-MBP handbook % yarn start
yarn run v1.22.11
$ next start
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Error: Could not find a production build in the '/Users/nick/dev/handbook/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
    at Server.readBuildId (/Users/nick/dev/handbook/node_modules/next/dist/server/next-server.js:1573:23)
    at new Server (/Users/nick/dev/handbook/node_modules/next/dist/server/next-server.js:92:29)
    at NextServer.createServer (/Users/nick/dev/handbook/node_modules/next/dist/server/next.js:107:16)
    at async /Users/nick/dev/handbook/node_modules/next/dist/server/next.js:119:31
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by felixfbecker** [comment]
Ah, I would guess for `yarn/next start` (production testing) you first need to run `yarn/next build`.

What I've been using all week is `yarn dev`, which just needs that one command. Maybe we should update the instructions to point to `yarn dev` (I wrote these really quickly without fully understanding NextJS myself yet 😄 ).
